### ISSUE TITLE
"You do not have permission to view the requested page."

### ISSUE THREAD

**Issue by javery86** [juho-jaakkola/elgg-notifier#38] opened 2017-12-17 21:30 UTC
I receive the error ""You do not have permission to view the requested page." anytime I try to click on "You have a new private message" for anyone that isn't an administrator.

**Comment by juho-jaakkola** [comment] 2017-12-18 08:45
Which plugin has provided that private message? The "Messages" plugin bundled with Elgg default package shouldn't be displayed by notifier at all, so I believe it has to be some other plugin.

Which version are you using of Elgg and Notifier?

**Comment by javery86** [comment] 2017-12-18 08:46
It occurs when using the hypeInbox plugin combined with your notifier plugin. If I disable the hypeInbox plugin, it works fine. Is there any way to make both work together?

**Comment by juho-jaakkola** [comment] 2017-12-18 08:48
What URL does the notification try to open?

**Comment by javery86** [comment] 2017-12-18 08:51
It tries to open a message that has a message ID exactly one number lower. For example, the message ID that arrives in the inbox might have a message ID of 350 but the notification will try to open a link with an ID of 351. I did notice that the message ID it tries to open is the same message ID that was originally sent by the sender. So apparently, when the message arrives in the receiver’s inbox, it gets another ID one number higher.

**Comment by juho-jaakkola** [comment] 2017-12-18 08:55
I think both user's have their own copy of the message. Therefore there are two IDs; One for each user.

The problem appears to be that for some reason Elggs notification system tries to generate the notification from the wrong copy of the message.

**Comment by juho-jaakkola** [comment] 2017-12-18 08:57
Can you check whether the ID of the message mentioned in the notification matches the ID of the message meant for the other user?

**Comment by javery86** [comment] 2017-12-18 08:57
I see. Would you happen to know how to fix it?

**Comment by javery86** [comment] 2017-12-18 08:58
It does match. It matches the ID from the original sender.

**Comment by juho-jaakkola** [comment] 2017-12-18 09:21
That sounds like a problem in the hypeInbox plugin. Notifier simply processes the data provided to it by the notifications system, and it seems the data is already faulty before Notifier starts to process it.

**Comment by javery86** [comment] 2017-12-18 09:27
I see. Well, it could have been great. Lol!

**Comment by juho-jaakkola** [comment] 2017-12-18 09:30
I'm closing the issue, because the problem is not caused by notifier.

**Closed as completed by juho-jaakkola** 2017-12-18 09:30 UTC
